[package]
name = "wasm-tools"
version = "0.1.0"
edition = "2021"
authors = ["starneko"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
md-5 = "0.10"
sha1 = "0.10"
sha2 = "0.10"
hex = "0.4"
base64 = "0.22"

[profile.release]
opt-level = "s"
lto = true
